### PR TITLE
Support ActiveSupport::RedisCacheStore

### LINKED ISSUE #281: Support RedisCacheStore (new in Rails 5.2)
After upgrading my app to Rails 5.2.0rc1, I'm occasionally getting the following error:
`Redis::CommandError: ERR value is not an integer or out of range`

Google says this error is caused by not passing the `raw` option when writing to Redis, then later incrementing the key. This appears to be fixed in this library for other forms of Redis caching, but not for the new ActiveSupport::Cache::RedisCacheStore.

Previous (working) config:
Ruby 2.5.0
Rails 5.1.4
ReadThisStore
Hiredis (driver)

Current (non-working) config:
Ruby 2.5.0
Rails 5.2.0rc1
RedisCacheStore
Hiredis (driver)

### PR DESCRIPTION
**Pull request by brian-kephart**
Fixes #281. Thanks for the good test suite, it prevented many problems. This PR passes Travis & Rubocop.

### CODE REVIEW

**Comment by grzuy** [comment]
> Fixes #281.

Thanks!

> Thanks for the good test suite, it prevented many problems.

Thank a lot for the feedback. I especially appreciate you noticing that, given that making the test suite robust was the main focus a couple of months ago (https://github.com/kickstarter/rack-attack/issues/293). Any other feedback about ways to improve it more very welcomed!

> This PR passes Travis & Rubocop.

Thanks for checking rubocop also.

**Comment by grzuy** [comment]
I want to code review and test this a bit more before merging. Will do as soon as I can. Will let you know.
Thanks again.

**Comment by brian-kephart** [comment]
Sounds good. Let me know if you have questions, or if anything's unclear.

**Comment by brian-kephart** [comment]
I change my initializer to:
```ruby
throttle('req/ip', :limit => 2, :period => 10) do |req|
  req.ip # unless req.path.start_with?('/assets')
end
```

...and now I can reproduce the error reliably. If I have the app running, then stop and restart Redis, the second request produces the error. Subsequent requests reproduce it until the 10sec timeout period expires.

Why? No idea.

**Comment by brian-kephart** [comment]
I put the repro on github [here](https://github.com/brian-kephart/rack-attack-test).

**Comment by brian-kephart** [comment]
Closing. See notes on #281.

**Comment by morgoth** [comment]
@brian-kephart I'm just debugging issues with Rails 5.2 using built in Redis cache handler and rack attack keys in Redis that don't expire. It looks like your PR could fix it. Why it was closed?

**Comment by brian-kephart** [comment]
The only errors I could reliably reproduce were solved another way, see #281 as mentioned above. I haven't seen these errors again despite weeks of use.

I think @grzuy would be open to merging this, but only with a reliable repro and a test. Current tests pass using the RedisCacheStore, so if it's really not working then there's something not covered by the tests.

**Comment by grzuy** [comment]
@brian-kephart @morgoth I was able to add a test reproducing the issue, see commits in https://github.com/kickstarter/rack-attack/pull/350.

This PR can no longer be merged because the original repo was deleted. I am cherry-picking the commit anyways.

Thank you both!

**Comment by brian-kephart** [comment]
Thanks @grzuy for your patience and persistence on this!

**Pull request closed without merging**
