### PR TITLE
Use `&block` as argument for all constructor

### PR DESCRIPTION
**Pull request by zerosign**
- Prefer `&block` rather than `block` for all constructor
- Add custom error if `developer` didn't specify `block` to be passed
  into constructor.
- Use `assert_nil` for Minitest
- Add `.gitignore` for emacs

### CODE REVIEW

**Comment by grzuy** [comment]
Hi @zerosign,

Thanks for contributing with rack-attack!

It seems like the `&block` changes are mixed with other unrelated changes. I find it better for everyone if different changes are part of different pull requests, which makes code review easier, and can keep discussions focused on one particular concern at a time.

That said, can you please either change this PR or open a new one just with the `&block` changes?

Thanks again!

**Comment by zerosign** [comment]
hi @grzuy, ok,  I'll try to update this branch soon

**Comment by grzuy** [comment]
Thank you @zerosign. Let me know if you need any help.

**Comment by grzuy** [comment]
Closing for now.

You can re-open on a separate one once you update the branch.

Thank you again!

**Pull request closed without merging**
