### PR TITLE
Fix several code style offenses

### PR DESCRIPTION
**Pull request by lmansur**
As @ktheory suggested in #219, this is an attempt keep the project up to date with the [community style guide](https://github.com/bbatsov/ruby-style-guide).

This is a good space to discuss what to adopt and what not to adopt from the guide. Should we set some guidelines or just use Rubocop? Or just ignore style all together?

I feel like following some kind of guideline helps the code be more consistent and less of a hassle to understand.

### CODE REVIEW

**Comment by grzuy** [comment]
Hi @lmansur 

> This is a good space to discuss what to adopt and what not to adopt from the guide. Should we set some guidelines or just use Rubocop? Or just ignore style all together?

If adopting a styleguide, then i think it probably makes sense to use something like rubocop so it's easy to continue to enforce it for future changes

> I feel like following some kind of guideline helps the code be more consistent and less of a hassle to understand

I agree

**Comment by lmansur** [comment]
With that in mind, should we add a section on Rubocop to the `Contributing` section of the README?

What about adding a static code analyzer such as CodeClimate or Hound?

**Comment by lmansur** [comment]
The PR is done.

@frewsxcv what are your thoughts on setting up a CodeClimate hook to ensure we are always merging quality code?

**Comment by lmansur** [comment]
Fixed conflicts.

**Comment by grzuy** [comment]
Did you run any `rubocop` command to spot these offenses? Was that run with any particular rubocop config file that you have?

Thanks.

**Comment by lmansur** [comment]
@grzuy I just ran `rubocop` in the shell. It is using the default config, I didn't overwrite it.

**Comment by grzuy** [comment]
@lmansur Gotcha, however if i run `rubocop` in this branch i still get a lot of offenses. Does the same happen to you?

**Comment by grzuy** [comment]
What about pausing here for a moment, and discuss what we actually want to do, how and why in this issue i opened: https://github.com/kickstarter/rack-attack/issues/302? Then we can either move on with this or open new PR depending on what we want out of it.

:-)

**Comment by lmansur** [comment]
>Gotcha, however if i run rubocop in this branch i still get a lot of offenses. Does the same happen to you?

@grzuy Yes, there are still a lot of offenses in the project. My intention here was not to fix all of them at once. I wanted to start with only a few so the reviewers could weigh in on them.

I will move the discussion to the issue #302.

**Comment by lmansur** [comment]
@grzuy I'm closing this PR for now in favor of #330.

**Comment by grzuy** [comment]
Sounds good, thanks! :-)

**Pull request closed without merging**
