### PR TITLE
[Fixes #302] Initial style guide adoption

### LINKED ISSUE #302: Stick to a ruby style guide
As rack-attack gem developers
We want to stick to a ruby code style guide
So that codebase is consistent and there's less decisions to be made about code style when coding

Idea brought up by @lmansur in https://github.com/kickstarter/rack-attack/pull/284

### PR DESCRIPTION
**Pull request by lmansur**
As discussed in #302, this is the first step in adopting a style guide.
This PR will fix all layout offenses in both the lib and the specs. I'll also update the contribution guide to mention the guide and Rubocop.

Still a work in progress.

### CODE REVIEW

**Comment by grzuy** [comment]
Thank you! :tada:

**Comment by lmansur** [comment]
I was still working on the `CONTRIBUTING` section hahaha
I'll open a new PR for that.

**Comment by grzuy** [comment]
Haha!

Sorry for that. Just realized the description included "Still work in progress".
Feel free to prepend something like `[WIP]` to the title next time if you want :-)

**Comment by lmansur** [comment]
Will do!

**Pull request merged**
