### PR TITLE
Make it clear that the cache store can be required

### PR DESCRIPTION
**Pull request by frenkel**
In order to prevent issues such as #225

### CODE REVIEW

**Comment by lmansur** [comment]
We use `Rails.cache` as a fall back in case you didn't configure `Rack::Attack::Cache.store`. Depending on your Rails version, `Rails.cache` in development environment uses `NullStore`, which doesn't actually store anything.

I think we could add some kind of notice regarding this possible case to avoid unnecessary debugging.

**Comment by grzuy** [comment]
Agree.

E.g. https://github.com/kickstarter/rack-attack/pull/274 was an attempt to aid users in debugging store config errors, but there's definitely room for more improvement. Either by giving better warning/errors and/or clearer docs.

**Comment by grzuy** [comment]
Created a new issue to track that need: https://github.com/kickstarter/rack-attack/issues/300

**Comment by grzuy** [comment]
Closing this PR for now given the conversation stalled, plus there were other changes which were trying to solve the same confusion as part of https://github.com/kickstarter/rack-attack/issues/300.

@frenkel Thank you for trying to contribute anyway. Let me know if you still think what you were trying to solve isn't yet covered, so we can continue discussing how to do that.

**Pull request closed without merging**
