### PR TITLE
Pass `raw: true` to prevent Ruby de/serialization. This is to make it po...

### PR DESCRIPTION
**Pull request by stanhu**
...ssible

to implement something like:

```store.write(key, 0, :expires_in => expires_in)```

See #113

### CODE REVIEW

**Comment by stanhu** [comment]
Is it better to pass options to both `read` and `write`? I noticed the Dalli proxy code forced usage of raw mode.

**Comment by ktheory** [comment]
@stanhu: looks good. thanks.

**Comment by ktheory** [comment]
@stanhu: Is this going to cause errors when deployed?

E.g., an app has a bunch of marshalled values in redis already. When they deploy this update, Rack::Attack will read them as raw values instead.

**Comment by stanhu** [comment]
@ktheory, yes it is a potential issue. We could make it default to marshalled values and use the options to override this behavior. But there is an inconsistency already in that the `increment` function uses raw values and the `read` uses marshalled values, which is what caused me hours of debugging. Thoughts?

**Comment by ktheory** [comment]
@stanhu: ok, so the only time Rack::Attack `read`s keys is in Fail/Allow2Ban. And anyone using Fail/Allow2Ban with redis would already be getting these serialization errors.

So it seems like this is strictly an improvement; not a gotcha for any redis users. :smile:

**Comment by stanhu** [comment]
@ktheory: Right, thanks!

**Pull request merged**
