### PR TITLE
RedisStoreProxy support connection pool

### PR DESCRIPTION
**Pull request by tumayun**

### CODE REVIEW

**Comment by tumayun** [comment]
How nothing happened?

**Comment by tumayun** [comment]
@ktheory ktheory

**Comment by ktheory** [comment]
Hi @tumayun: I have not had a chance to review this yet.

Could you please add a description to this Pull Request explaining what feature it's adding, and why it's useful?

**Comment by tumayun** [comment]
Hi @ktheory
Redis supports connection pool.

**Pull request closed without merging**
