### PR TITLE
Controversial Language Change Suggestion

### PR DESCRIPTION
**Pull request by renee-travisci**
Hello! 
  At Travis CI we've decided to change our usage of Whitelist/Blacklist to the less racially charged language of Safelist/Blocklist. We are using rack-attack and would love to use an updated version with our language choices if you are open to this change. I'm not sure how you would like to change the versioning of this so I didn't add any changes there. I know this would require users to update all of their whitelist/blacklist method calls to the new verbiage, which might annoy a number of end users. However, we did this with a simple find and replace (and method aliases until this change is welcomed). I added the depreciation warnings for the old method names to help users, however if anyone is relying on the rack.attack.match_type I changed it to safelist/blocklist (wasn't sure how to deprecate that nicely). 
Thanks!
**Renée

### CODE REVIEW

**Comment by ktheory** [comment]
@renee-travisci Thank you so much! This PR made my day. 😍 

`safelist` & `blocklist` are better & more inclusive names, so this isn't controversial to me. And you even added deprecation warnings and tests. 👍 💯 

Lemme get tests passing on master again, and double-check that the upgrade path is smooth w/ deprecation warnings. Then I'll merge & release.

**Comment by renee-travisci** [comment]
@ktheory I've got a branch with working master tests! was just about to PR :)

**Comment by ktheory** [comment]
I cleaned up a few things in #183 and just [released v5.0.0.beta1](https://rubygems.org/gems/rack-attack/versions/5.0.0.beta1).

@renee-travisci: mind giving that a whirl on TravisCI's app and letting me know if you have any trouble?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@ktheory thank you so much! We deployed 0.5.0.beta1 to production today -- running smooth so far!

**Comment by quecas-de-don-isidro** [comment]
Hmmm. I post this and less than an hour later someone signs me up with my private email for a trans advocacy group. I've requested the IP address that my email was submitted from. I hope that whoever is conducting this harassment was smart enough to use a proxy.

**Comment by ktheory** [comment]
Hi @quecas-de-don-isidro,

The author’s commitment and what I think of it are irrelevant and off-topic.

Per [Rack::Attack’s Code of Conduct](https://github.com/kickstarter/rack-attack/blob/master/CODE_OF_CONDUCT.md):

> Examples of unacceptable behavior include … derogatory comments or personal attacks, trolling, public or private harassment.

Please refrain from personal attacks.

I’m deleting the parts of your comments that I judge to be a personal attack and/or off-topic.

**Pull request merged**
